[package]
org = "lorenzodonati"
name = "ESTRA_Ballerina"
version = "0.1.0"
distribution = "2201.6.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "lorenzodonati"
name = "ESTRA_Templates_Sequences"
version = "0.1.0"
repository="local"